
device: cuda
amp: false

folder: checkpoint
name: gigagan-upscaler
tag: date

log_interval: 100
save_every: 10000
running_every: 100

data:
  image_folder: ./data/imagenet
  resolution: 256
  scale_factor: 4
  interpolation: 3
  hflip: 0.5
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  resize_scale: [0.5, 1.0]

loader:
  batch_size: 2
  pin_memory: true
  shuffle: true
  drop_last: true
  num_workers: 2

g:
  z_dim: 128
  c_dim: 0
  w_dim: 512
  img_channels: 3
  img_resolution: 256
  mapping_kwargs:
    num_layers: 4
    embed_features: null
    layer_features: null
    activation: lrelu
    lr_multiplier: 0.01
    w_avg_beta: 0.995
  synthesis_kwargs:
    dim: 64
    up_dim_multi: [16, 8, 4, 2, 1]
    down_dim_multi: [2, 4, 8]
    num_blocks: 5
    self_attn_depths:
      16: 4
      32: 2
    self_attn_heads:
      16: 8
      32: 8
    channel_max: 512
    num_fp16_res: 0
    self_attn_ratio: 1.4
    self_attn_mlp_ratio: 4.0
    self_attn_norm: true
    residual_gain: 0.4
    attn_residual_gain: 0.3
    resample_filter: [1, 3, 3, 1]
    activation: lrelu

d:
  c_dim: ${g.c_dim}
  img_resolution: ${g.img_resolution}
  img_channels: ${g.img_channels}
  architecture: resnet
  channel_base: 32768
  channel_max: 512
  num_fp16_res: 0
  conv_clamp: null
  cmap_dim: null
  block_kwargs:
    activation: lrelu
    resample_filter: [1, 3, 3, 1]
  epilogue_kwargs:
    mbstd_group_size: 4
    mbstd_num_channels: 1
    activation: lrelu


g_optim:
  lr: 0.0025
  betas: [0.0, 0.99]
  weight_decay: 0.00001


d_optim:
  lr: 0.0025
  betas: [0.0, 0.99]
  weight_decay: 0.00001


loss:
  gan_type: hinge
  gp_every: 16
  gp_lambda: 0.2048
  gan_lambda: 1.0
  lpips_lambda: 100.0


train:
  iterations: 200000
  batch_size: 16
  ema_beta: 0.9912
